language: php
dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=">=5.4.0 <5.4.20"
  - LARAVEL_VERSION=">=5.4.20 <5.5.0"
  - LARAVEL_VERSION="5.5.*"
  - LARAVEL_VERSION="5.5.*" HORIZON=1
  - LARAVEL_VERSION="5.6.*"
  - LARAVEL_VERSION="5.6.*" HORIZON=1
  - LARAVEL_VERSION="5.7.*"
  - LARAVEL_VERSION="5.7.*" HORIZON=1
  - LARAVEL_VERSION="5.8.*"
  - LARAVEL_VERSION="5.8.*" HORIZON=1
  - LARAVEL_VERSION="6.0.*"
  - LARAVEL_VERSION="6.0.*" HORIZON=1
  - LUMEN_VERSION="5.4.*"
  - LUMEN_VERSION="5.5.*"
  - LUMEN_VERSION="5.6.*"
  - LUMEN_VERSION="5.7.*"
  - LUMEN_VERSION="5.8.*"
  - LUMEN_VERSION="6.0.*"

matrix:
  exclude:
    - php: 5.6
      env: LARAVEL_VERSION="5.5.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.5.*" HORIZON=1
    - php: 5.6
      env: LUMEN_VERSION="5.5.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.6.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.6.*" HORIZON=1
    - php: 5.6
      env: LUMEN_VERSION="5.6.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.7.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.7.*" HORIZON=1
    - php: 5.6
      env: LUMEN_VERSION="5.7.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.8.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.8.*" HORIZON=1
    - php: 5.6
      env: LUMEN_VERSION="5.8.*"
    - php: 5.6
      env: LARAVEL_VERSION="6.0.*"
    - php: 5.6
      env: LARAVEL_VERSION="6.0.*" HORIZON=1
    - php: 5.6
      env: LUMEN_VERSION="6.0.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.5.*" HORIZON=1
    - php: 7.0
      env: LARAVEL_VERSION="5.6.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.6.*" HORIZON=1
    - php: 7.0
      env: LUMEN_VERSION="5.6.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.7.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.7.*" HORIZON=1
    - php: 7.0
      env: LUMEN_VERSION="5.7.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.8.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.8.*" HORIZON=1
    - php: 7.0
      env: LUMEN_VERSION="5.8.*"
    - php: 7.0
      env: LARAVEL_VERSION="6.0.*"
    - php: 7.0
      env: LARAVEL_VERSION="6.0.*" HORIZON=1
    - php: 7.0
      env: LUMEN_VERSION="6.0.*"
    - php: 7.1
      env: LARAVEL_VERSION="6.0.*"
    - php: 7.1
      env: LARAVEL_VERSION="6.0.*" HORIZON=1
    - php: 7.1
      env: LUMEN_VERSION="6.0.*"

before_install:
  - if [ -n "$LARAVEL_VERSION" ]; then composer remove --dev --no-update "laravel/lumen-framework"; fi
  - if [ -n "$LARAVEL_VERSION" ]; then composer require --no-update "laravel/framework:$LARAVEL_VERSION"; fi
  - if [ -n "$LUMEN_VERSION" ]; then composer remove --dev --no-update "laravel/framework"; fi
  - if [ -n "$LUMEN_VERSION" ]; then composer require --no-update "laravel/lumen-framework:$LUMEN_VERSION"; fi
  - if [ -z "$HORIZON" ]; then composer remove --dev --no-update "laravel/horizon"; fi

install: travis_retry composer install --prefer-dist --no-interaction --no-suggest

before_script: SUPERVISE=no travis_retry ./start-cluster.sh || { cat ./cluster/*.log; false; }

script: vendor/bin/phpunit --exclude-group ${LUMEN_VERSION:+laravel-only},${HORIZON:-horizon}
